# Generated by Django 3.0.5 on 2020-05-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fir',
            name='phone',
        ),
    ]
